version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:1.24.4-bcc31d32159f
    container_name: jenkins
    restart: always
    user: root                          
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      TZ: Asia/Shanghai
    entrypoint: /bin/bash -c -- " ulimit -c unlimited && /opt/java/openjdk/bin/java -Duser.home=/var/jenkins_home -Djenkins.model.Jenkins.slaveAgentPort=50000 -jar /usr/share/jenkins/jenkins.war"
    volumes:
    - /Users/admin/Desktop/docker/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock