version: "2.4"

services:
  redis:
    image: redis:3.2.11
    hostname: redis
    restart: always

  mysql:
    image: mysql:latest
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=subscan
    restart: always